version: '3'

volumes:
  postgres_data:

services:
  db: # database server
    restart: always
    image: postgres:11.8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web: # django server
    restart: always
    build: .
    command: python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
